### ISSUE TITLE
Studio-client Versions don't match coremedia versioning (no minor version)

### ISSUE THREAD

**Issue by Ahoi-IT** [tallence/core-forms#108]
Hello @timolemke . 

First of all, thanks for your great work and for providing this cool extension in 2301.1 already. 

I've tried to merge your current master branch into our project-specific clone and got some merge conflicts regarding the version numbers.

CoreMedia upstream uses version number without minor versions (e.g. 2301.1) for maven dependencies, but with minor versions (e.g. 2301.1.0) for studio modules.

**Example**: 
from [https://github.com/tallence/core-forms/blob/master/apps/studio-client/shared/js/form-editor/package.json](https://github.com/tallence/core-forms/blob/master/apps/studio-client/shared/js/form-editor/package.json):
```
"@coremedia/studio-client.base-models": "2301.1"
```
vs. [https://github.com/coremedia-contributions/coremedia-blueprints-workspace/blob/cmcc-11-2301/apps/studio-client/apps/main/blueprint-forms/package.json](https://github.com/coremedia-contributions/coremedia-blueprints-workspace/blob/cmcc-11-2301/apps/studio-client/apps/main/blueprint-forms/package.json):
```
"@coremedia/studio-client.base-models": "2301.1.0"
```

What's the idea behind it? Why are you using shorter version numbers than coremedia. Does this work in your environment?

**Comment by timolemke** [comment]
Hi @Ahoi-IT 
thanks for the hint. There is no idea behind using "2301.1", it's simply a mistake, you are right.
I will create a PR here and in https://github.com/tallence/core-forms/
