### ISSUE TITLE
Studio API Change CM9

### ISSUE THREAD

**Issue by winniae** [tallence/core-forms#25]
Hi, ich habe den Form Editor auf CM9 1804.1 integriert und bekomme einen Fehler, wenn ich das Studio Plugin baue.
Anscheinend gibt es _enableFocusableContainer_ nicht mehr, habe es durch das Property _focusableContainer_ ersetzt. Kenne mich leider zu wenig aus um zu wissen was es ausmacht 8 )

**Comment by timolemke** [comment]
Hallo Winfried, danke für Deinen Input!
Schauen wir uns an.

**Comment by TallenceJanHendrikPopp** [comment]
Hi,
für die Formularelemente haben wir den Header des Panels ausgetauscht. Bei der Konfiguration des Headers haben wir uns an dem Header von CoreMedia für die CollapsiblePanel orientiert. Ich habe jetzt einmal überprüft, was diese Einstellung für eine Auswirkung hat.

Wenn man innerhalb eines Dokuments **Tab** drückt, wird immer das nächste Element ausgewählt. Bei den CollapsiblePanel ist der Fokus dann auf dem "Pfeil" zum aus und einklappen. Wenn der Fokus auf diesem "Pfeil" liegt und die Option enableFocusableContainer auf false gesetzt ist, kann weiterhin mit den Pfeiltasten innerhalb der Dokumentenform gescrollt werden. ist die Option jedoch auf true gesetzt, so kann der Fokus innerhalb des Containers gewechselt werden.

In unserem Beispiel würde dann mit den Pfeiltasten nicht mehr gescrollt werden, sondern es könnte nur noch der Fokus von dem "Pfeil" auf das "Löschen" Symbol gewechselt werden. Es macht also durchaus Sinn, den Wert auf false zu setzten.

CoreMedia hat diese Option auch an einigen Stellen gesetzt und dementsprechend beim Update angepasst. Ein Beispiel kann man hier finden: https://github.com/coremedia-contributions/coremedia-blueprints-workspace/blob/cms-9-1804/modules/extensions/taxonomy/taxonomy-studio/src/main/joo/com/coremedia/blueprint/studio/taxonomy/selection/TaxonomySuggestionsLinkListPanel.mxml
In dem Beispiel wurde die Konfiguration also per  xmlns:u="exml:untyped" Namespace weiterhin gesetzt.

Ich würde jetzt noch einmal in einer  CM9 1804.1 Testumgebung testen, ob die von CoreMedia gewählte Anpassung auch für unsere Formelemente funktioniert oder focusableContainer auf false gesetzt werden sollte.

**Comment by winniae** [comment]
Hallo Jan, danke für die ausführliche Erklärung 8) In dem zitierten Panel von CoreMedia wurde enableFocusableContainer ja auch in focusableContainer umbenannte, also ist es zumindest nichts komplett verkehrt... aber ja klar testen, habe leider 0 Erfahrung mit Studio :-#

**Comment by timolemke** [comment]
Wir haben beide Varianten verwendet:
            u:focusableContainer="false"
            u:enableFocusableContainer="false"
Das sollte also mit allen cm9 Versionen funktionieren. "u" ist der Untyped Namespace "exml:untyped".
