### ISSUE TITLE
Suggestion for new form field type: DatePicker

### ISSUE THREAD

**Issue by winniae** [tallence/core-forms#30]
Hab ich mir schon eingebaut, aber habe gerade keine Resourcen für Studio um etwas sinvolles als PR bereitzustellen...

**Comment by timolemke** [comment]
Has been solved in the meantime. See 
https://github.com/tallence/core-forms/blob/master/form-editor-cae/src/main/java/com/tallence/formeditor/cae/elements/DateField.java
https://github.com/tallence/core-forms/pull/57
