### ISSUE TITLE
Update to 1907.02

### ISSUE THREAD

**Issue by TallenceJanHendrikPopp** [tallence/core-forms#41]

**Comment by mgoellnitz** [comment]
Is this just a marker issue or is someone actually working on it? We are just about to consolidate our CMS-9 based branch/fork and would then head for CMCC-10.
(FYI @blackappsolutions)

**Comment by TallenceJanHendrikPopp** [comment]
We are already working on the issue and will provide a release branch by the end of the week (1907.02).
