### ISSUE TITLE
Command to enable extension uses wrong parameter

### ISSUE THREAD

**Issue by dstrasse** [tallence/core-forms#71]
The Maven command to enable the extension uses the wrong parameter. Instead of  ```-Denable=formeditor-extension``` it needs to use the folder name used for the git submodule initialization, i.e. ```-Denable=core-forms```

**Comment by timolemke** [comment]
@dstrasse thanks for the hint! Do you refer to the wrong extensions-command in the Readme? This should be resolved by the referenced PR. https://github.com/tallence/core-forms/pull/72 (just created)

**Comment by dstrasse** [comment]
@timolemke, Yes I was referring to the readme. Thanks for fixing.
