### ISSUE TITLE
Studio build in version 2201.2.0 not work

### ISSUE THREAD

**Issue by anthofma** [tallence/core-forms#88]
Error: Cannot handle multiple versions of the same package in one workspace! Please check dependencies.

core-forms\apps\studio-client\apps\main\form-editor-studio-plugin\package.json 
core-forms\apps\studio-client\shared\js\form-editor\package.json

needs Coremedia-Version 2201.2.0 and jangaroo-Version 1.1.1

**Comment by timolemke** [comment]
Solved when https://github.com/tallence/core-forms/pull/89 is merged

**Comment by timolemke** [comment]
Fixed by #89 
Thanks https://github.com/Ahoi-IT !
